config/routes.rb
Rails.application.routes.draw do
  resources :pictures

  resources :list_of_waterfalls

  get 'welcome/index'

  root 'welcome#index'

end

app/models/list_of_waterfall.rb
class ListOfWaterfall < ActiveRecord::Base
end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/list_of_waterfalls_controller.rb
class ListOfWaterfallsController < ApplicationController
  before_action :set_list_of_waterfall, only: [:show, :edit, :update, :destroy]

  # GET /list_of_waterfalls
  # GET /list_of_waterfalls.json
  def index
    @list_of_waterfalls = ListOfWaterfall.all
  end

  # GET /list_of_waterfalls/1
  # GET /list_of_waterfalls/1.json
  def show
  end

  # GET /list_of_waterfalls/new
  def new
    @list_of_waterfall = ListOfWaterfall.new
  end

  # GET /list_of_waterfalls/1/edit
  def edit
  end

  # POST /list_of_waterfalls
  # POST /list_of_waterfalls.json
  def create
    @list_of_waterfall = ListOfWaterfall.new(list_of_waterfall_params)

    respond_to do |format|
      if @list_of_waterfall.save
        format.html { redirect_to @list_of_waterfall, notice: 'List of waterfall was successfully created.' }
        format.json { render :show, status: :created, location: @list_of_waterfall }
      else
        format.html { render :new }
        format.json { render json: @list_of_waterfall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /list_of_waterfalls/1
  # PATCH/PUT /list_of_waterfalls/1.json
  def update
    respond_to do |format|
      if @list_of_waterfall.update(list_of_waterfall_params)
        format.html { redirect_to @list_of_waterfall, notice: 'List of waterfall was successfully updated.' }
        format.json { render :show, status: :ok, location: @list_of_waterfall }
      else
        format.html { render :edit }
        format.json { render json: @list_of_waterfall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_of_waterfalls/1
  # DELETE /list_of_waterfalls/1.json
  def destroy
    @list_of_waterfall.destroy
    respond_to do |format|
      format.html { redirect_to list_of_waterfalls_url, notice: 'List of waterfall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list_of_waterfall
      @list_of_waterfall = ListOfWaterfall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_of_waterfall_params
      params.require(:list_of_waterfall).permit(:name, :height, :locality, :country, :description)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.fetch(:picture, {})
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_of_waterfalls_helper.rb
module ListOfWaterfallsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<li><a class="action" href="http://localhost:3000/pictures"</a>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/list_of_waterfalls/_form.html.erb
<%= form_for(@list_of_waterfall) do |f| %>
  <% if @list_of_waterfall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list_of_waterfall.errors.count, "error") %> prohibited this list_of_waterfall from being saved:</h2>

      <ul>
      <% @list_of_waterfall.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :locality %><br>
    <%= f.text_field :locality %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/list_of_waterfalls/edit.html.erb
<h1>Editing list_of_waterfall</h1>

<%= render 'form' %>

<%= link_to 'Show', @list_of_waterfall %> |
<%= link_to 'Back', list_of_waterfalls_path %>

app/views/list_of_waterfalls/index.html.erb
<h1>List of waterfalls</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Height</th>
      <th>Locality</th>
      <th>Country</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @list_of_waterfalls.each do |list_of_waterfall| %>
      <tr>
        <td><%= list_of_waterfall.name %></td>
        <td><%= list_of_waterfall.height %></td>
        <td><%= list_of_waterfall.locality %></td>
        <td><%= list_of_waterfall.country %></td>
        <td><%= list_of_waterfall.description %></td>
        <td><%= link_to 'Show', list_of_waterfall %></td>
        <td><%= link_to 'Edit', edit_list_of_waterfall_path(list_of_waterfall) %></td>
        <td><%= link_to 'Destroy', list_of_waterfall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List of waterfall', new_list_of_waterfall_path %>

app/views/list_of_waterfalls/new.html.erb
<h1>New list_of_waterfall</h1>

<%= render 'form' %>

<%= link_to 'Back', list_of_waterfalls_path %>

app/views/list_of_waterfalls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list_of_waterfall.name %>
</p>

<p>
  <strong>Height:</strong>
  <%= @list_of_waterfall.height %>
</p>

<p>
  <strong>Locality:</strong>
  <%= @list_of_waterfall.locality %>
</p>

<p>
  <strong>Country:</strong>
  <%= @list_of_waterfall.country %>
</p>

<p>
  <strong>Description:</strong>
  <%= @list_of_waterfall.description %>
</p>

<%= link_to 'Edit', edit_list_of_waterfall_path(@list_of_waterfall) %> |
<%= link_to 'Back', list_of_waterfalls_path %>

app/views/pictures/index.html.erb
<!DOCTYPE html>
<html>
<body>

  <h2>More waterfall picrures</h2>
  <img src="https://static3.crated.com/FiPVXdgBxpteDALNJTVx6PtpS4g=/fit-in/330x330/filters:quality(80)/crated/thumbs/art/2014/09/02/9f990e62f497fbb4eef45fd45e3aab29/960.jpg">
<img src="https://s-media-cache-ak0.pinimg.com/originals/7f/02/b3/7f02b3616b87dcc9d77eb7ab5e0376e1.jpg">

<img src="http://outdoor.geocities.jp/takinoaruhuukei2/hukiwarinotaki.jpg">
<img src="http://thumb.canhdep.net/w330/image/2016/06/hanh-trinh-chinh-phuc-dong-thac-bac-tren-suon-tay-yen-tu-suoi-mo-1466928604-576f8ddc0962f.jpg">
<img src="http://outdoor.geocities.jp/redsox20jp/image277.jpg">

<img src="http://gopb.ru/wp-content/uploads/2017/05/1-18.jpg">
<img src="https://www.thebrokebackpacker.com/wp-content/uploads/2015/10/shutterstock_534743974-330x222.jpg">

<img src="http://cdn.allfun.md/2016/04/12/14/570cdccb4f29b.jpg">
<img src="http://www.sunflowercilento.com/assets/images/cascata.png">
<img src="http://m.map.com.tw/travel/CompLogoPic/135-002414.jpg">




</body>
</html>

app/views/welcome/index.html.erb
<header class="hero-search-filter">
  <div class="hero-search-filter-content">
  </form>

</div>
</header>

<h1>World's top five waterfalls</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Height</th>
      <th>Locality</th>
      <th>Country</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><a href="https://en.wikipedia.org/wiki/Angel_Falls">Angel Falls		Venezuela</a></td>

      <td>979 metres (3,212 ft)</td>
      <td>Canaima National Park, Bolívar</td>
      <td>Venezuela</td>
      <td>The falls are along a fork of the Rio Kerepacupai Meru which flows into the Churn River, a tributary of the Carrao River, itself a tributary of the Orinoco River.</td>

    </tr>
    <tr>
      <td><a href="https://en.wikipedia.org/wiki/Tugela_Falls">Tugela Falls</a></td>
      <td>948 meters (3,110 ft)</td>
      <td>KwaZulu-Natal</td>
      <td>South Africa</td>
      <td>The source of the Tugela River (Zulu for &#39;sudden&#39;) is the Mont-Aux-Sources plateau which extends several kilometers beyond The Amphitheater escarpment from which the falls drop.</td>
    </tr>
    <tr>
      <td><a href="https://en.wikipedia.org/wiki/Tres_Hermanas_Falls">Tres Hermanas Falls</a></td>
      <td>914 metres (2,999 ft)</td>
      <td>Otishi National Park, Junin</td>
      <td>Peru</td>
      <td>Tres Hermanas is a tiered waterfall, with three drops or sections. Its is located within a wet montane forest.</td>

    </tr>
    <tr>
      <td><a herf="https://www.worldwaterfalldatabase.com/waterfall/Oloupena-Falls-625 ">Olo&#39;upena Falls</a></td>
      <td>900 metres (2,953 ft)</td>
      <td>Molokai, Hawaii	</td>
      <td>United States</td>
      <td>The falls occur where a short, seasonal stream spills over the edge of one of the tallest sea-side cliffs of the world, located between the Pelekunu and Wailau valleys. </td>

    </tr>
    <tr>
      <td><a herf="https://commons.wikimedia.org/wiki/File:Vinnufossen,_Sunndal,_Norway_(front).jpg">	Vinnufossen</a></td>
      <td>860 meters (2,822 ft)</td>
      <td>Møre og Romsdal</td>
      <td>Norway</td>
      <td>The falls are part of the river Vinnu which flows down from the Vinnufjellet mountain and it is fed from the Vinnufonna glacier. The falls flow into the river Driva near the village of Hoelsand.</td>

    </tr>
  </tbody>
</table>



<a href="http://localhost:3000/pictures"><h3>Click here to view more pictures></h3></a>


<div class="wide-article-link">
  <div class="row">
    <div class="small-12 medium-9 columns">
      <h4 class="article-title">
        <div class="article-social">
          <!-- Begin Container -->
          <div id="container">
            <!-- Begin Masthead -->


            <span class="auto-style6"><strong><p>&nbsp;</p>

            </div>
            <!-- End Masthead -->

          </div>
        </div>
        <div class="small-12 medium-3 columns flex-container align-middle">
          <img src="http://img0.joyreactor.cc/pics/comment/art-fantasy-world-fantasy-art-Fantasy-11082.jpeg">
        </div>
      </div>
    </div>